### PR TITLE
Do not check for specific fields when a file is requested, only check a url is provided

### PR DESCRIPTION
**Pull request by fjvallarino**
@tejohnso please review

### CODE REVIEW

**Comment by tejohnso** [comment]
What's the back story?

**Comment by fjvallarino** [comment]
@tejohnso Storage component was not working properly with Rise Cache Java version. After a bit of debugging I found caching was only being applied if the requested URL followed certain format, which does not really affect how the download is performed. With this change, Storage component and Widgets using it, such as Image and Video folder, work properly.

**Comment by tejohnso** [comment]
It shouldn't go on to log "video command received" and call a video specific method if it's no longer just about video.  

Do you know why it was restricted only to video in the first place?

**Comment by olegrise** [comment]
The original requirement was that we need caching for video. Video caching was the biggest concern at that time.

**Comment by fjvallarino** [comment]
@tejohnso well, I wanted to change as little as possible, and this version of cache was already handing other kind of files with this procedure (it's not something I added).

**Comment by tejohnso** [comment]
@fjvallarino we need to adhere to the "leave it better than you found it" principle in these cases.  Incorrect logging and misleading method names really ought to be updated/refactored as we go.  I think we should prefer refactoring and incremental improvement over changing as little as possible.

**Comment by fjvallarino** [comment]
@tejohnso updated

**Comment by tejohnso** [comment]
:+1:

**Pull request merged**
