### PR TITLE
Added Logging to BQ

### PR DESCRIPTION
**Pull request by rodrigopavezi**
@tejohnso @fjvallarino please review. cheers

### CODE REVIEW

**Comment by tejohnso** [comment]
template suffix :)
:+1:

**Comment by rodrigopavezi** [comment]
@tejohnso @fjvallarino I got it working without the PipedStream classes. Could you please review? cheers

**Comment by fjvallarino** [comment]
:+1: Looks good for me

**Comment by tejohnso** [comment]
:+1:

**Comment by rodrigopavezi** [comment]
@fjvallarino thanks for the help on this one.

**Pull request merged**
